clear,clc;

% Call InCalcOut(*) function generated by AceGen

% Create a random input value xInput and show its value
xInput = rand()

% Analytical result
y_ay = 25 + xInput^2 + 1/xInput + sin(xInput)
dy_dx_ay = 2*xInput - 1/xInput^2 + cos(xInput)

% Call the function created by AceGen just like you would call any Matlab function
[yOutput,DyDxOutput] = InCalcOut(xInput)
